spring.application.name=backend

server.port=${PORT:8080}

spring.datasource.url=jdbc:mysql://root:JIbFAMRBcpWKRmgQNTFWwqpZvywrfpKn@mysql.railway.internal:3306/cancer_db
spring.datasource.username=cancer_db
spring.datasource.password=JIbFAMRBcpWKRmgQNTFWwqpZvywrfpKn

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

jwt.secret=${JWT_SECRET:change-this-secret-key-to-a-long-random-secret-key-for-production}
jwt.expiration=86400000         
